CREATE TABLE shifts (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    employee_name varchar(255),
    shift_date date,
    start_time varchar(255),
    end_time varchar(255),
    lunch_minutes integer NOT NULL,
    hours double precision NOT NULL,
    shift_type varchar(255),
    PRIMARY KEY (id)
);

CREATE TABLE employees (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255),
    employee_id varchar(255),
    password varchar(255),
    PRIMARY KEY (id),
    CONSTRAINT uk_employees_employee_id UNIQUE (employee_id)
);

CREATE TABLE manager_accounts (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    username varchar(255),
    password varchar(255),
    PRIMARY KEY (id)
);
