CREATE TABLE weekly_budgets (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    week_start date NOT NULL,
    hours double precision NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_weekly_budgets_week_start UNIQUE (week_start)
);
